'use strict'
/**
 * predictor/ensemble.js — v8
 *
 * 5-model sigmoid ensemble. Each model normalised to [0,1] via rank-percentile,
 * then combined through sigmoid(wA·sA + wB·sB + wC·sC + wD·sD + wE·sE + bias).
 * Weights trained walk-forward with L2 regularisation (scripts/train_weights.js).
 *
 *   MODEL A — Statistical z-score + 4 auxiliary signals (S3–S6)
 *     z-score = gap overdueness; S3 sum deviation; S4 digit momentum;
 *     S5 sum-bucket overdue (+0–7% gentle nudge);
 *     S6 pair-digit overdue (+0–7% gentle nudge — applies to pair/triple only)
 *     ALL signals merged in a SINGLE O(N) pass for performance.
 *
 *   MODEL B — Markov order-2 (transition probability)
 *     P(next | prev-2, prev-1); fallback order-1; fallback 1/216.
 *
 *   MODEL C — Time-of-day session model (frequency ratio)
 *     morning 6–12h / afternoon 12–18h / evening 18–6h
 *     When < 20 draws in session → weight=0, redistribute to A+B.
 *
 *   MODEL D — k-NN Temporal Similarity (pure-JS ML)
 *     Auto-disabled when learned weight wD < 0.
 *
 *   MODEL E — Python GBM prior (offline, from python/ml_output.json)
 *     Active when file present AND dataset grew ≤ 200 records since training.
 *
 * S2 Triple streak boost — applied AFTER ensemble:
 *   ratio = sinceTriple / 36;  ratio ≤ 1 → no boost;  max 1.5× at ratio ≥ 2
 *   Only fires when clearly overdue (not within normal variance of 36-draw gap).
 *
 * S5/S6 design note:
 *   These are gentle tie-breakers, NOT dominant signals.
 *   Max +7% each (combined ≤ +14.5%) prevents compounding bias from inflating
 *   triple scores above high-z normal combos.
 *
 * Diversity cap (selectTop10):
 *   max 2 triple, 4 pair, 4 normal per top-10.
 *   Bypass slot (z > 2.5, max 3): severely overdue combos forced in by z DESC.
 */

const path = require('path')
const fs = require('fs')
const modelD = require('./model_d')
const { runStatTests } = require('./stats_tests')

const HISTORY_FILE = path.join(__dirname, '../dataset/history.json')
const WEIGHTS_FILE = path.join(__dirname, '../dataset/model.json')
const GBM_FILE = path.join(__dirname, '../python/ml_output.json')
const GBM_MAX_STALENESS = 200  // records; invalidate GBM scores if dataset grew > this

// ── Learned weights (sigmoid ensemble) ────────────────────────────────────
// Trained by: node scripts/train_weights.js
// Falls back to fixed weights if file not found or parse error.

function sigmoid(x) { return 1 / (1 + Math.exp(-x)) }

let _learnedWeights = null
function loadLearnedWeights() {
  try {
    const raw = fs.readFileSync(WEIGHTS_FILE, 'utf8')
    const w = JSON.parse(raw)
    // Minimal validation — must have numeric weights
    if (typeof w.wA === 'number' && typeof w.wB === 'number') {
      // Only activate if training confirmed validation improvement (or flag absent = legacy)
      if (w.improvesValid === false) {
        _learnedWeights = null    // training found no improvement; keep fixed weights
      } else {
        _learnedWeights = w
      }
    } else {
      _learnedWeights = null
    }
  } catch (_) {
    _learnedWeights = null
  }
}
loadLearnedWeights()  // load once at startup

// Auto-reload when model.json changes on disk (e.g. after npm run train).
// fs.watchFile uses polling — reliable across all platforms, no ENOENT crash.
fs.watchFile(WEIGHTS_FILE, { interval: 5000, persistent: false }, () => {
  loadLearnedWeights()
})

// ── Model E: Python GBM scores (offline, optional) ────────────────────────
// Generated by: python python/ml_predictor.py  → python/ml_output.json
// Treated as a fixed prior distribution over combos. When stale (dataset grew
// > GBM_MAX_STALENESS records since GBM run), scores are ignored (sE = 0).

let _gbmScores = null
let _gbmTrainRecords = 0

function loadGBMScores() {
  try {
    const raw = fs.readFileSync(GBM_FILE, 'utf8')
    const obj = JSON.parse(raw)
    if (obj.scores && typeof obj.scores === 'object') {
      _gbmScores = obj.scores
      _gbmTrainRecords = obj.trainRecords || 0
    } else {
      _gbmScores = null
    }
  } catch (_) {
    _gbmScores = null
  }
}
loadGBMScores()

/** Returns GBM score map or {} when file absent / stale. */
function getGBMScores(currentN) {
  if (!_gbmScores) return {}
  if (Math.abs(currentN - _gbmTrainRecords) > GBM_MAX_STALENESS) return {}
  return _gbmScores
}
const SUM_COUNT = {
  3: 1, 4: 3, 5: 6, 6: 10, 7: 15, 8: 21,
  9: 25, 10: 27, 11: 27, 12: 25, 13: 21, 14: 15,
  15: 10, 16: 6, 17: 3, 18: 1,
}

function key(n1, n2, n3) { return `${n1}-${n2}-${n3}` }

function classify(a, b, c) {
  if (a === b && b === c) return 'triple'
  if (a === b || b === c || a === c) return 'pair'
  return 'normal'
}

const ALL_COMBOS = []
for (let a = 1; a <= 6; a++)
  for (let b = 1; b <= 6; b++)
    for (let c = 1; c <= 6; c++)
      ALL_COMBOS.push([a, b, c])

const ALPHA = 0.5  // Laplace smoothing constant for Markov model B

/**
 * Rank-percentile normalize a score map {key: number} → {key: [0,1]}.
 *
 * Assigns each combo its fractional rank: 0 = worst, 1 = best.
 * With 216 combos rank resolution is 1/215 ≈ 0.46%.
 *
 * Why rank instead of min-max:
 *   - Invariant to the *magnitude* of raw scores (kNN dist, z-score range, etc.)
 *   - Range stays [0,1] as N grows — learned weights stay calibrated
 *   - min-max range shifts as the dataset size changes, destabilising weights
 *
 * All-equal values → 0.5 (model is uninformative, treated as neutral).
 */
function rankNorm(scoreMap) {
  const keys = Object.keys(scoreMap)
  if (!keys.length) return scoreMap
  const sorted = keys.slice().sort((a, b) => scoreMap[a] - scoreMap[b])
  const n = sorted.length
  if (n === 1) return { [keys[0]]: 0.5 }
  const out = {}
  sorted.forEach((k, i) => { out[k] = i / (n - 1) })
  return out
}

// ── MODEL A: Statistical z-score + S3–S6 (single O(N) pass) ──────────────
/**
 * Model A: gap-based z-score with 4 auxiliary signals in ONE O(N) pass.
 *
 *   z = (currentGap – avgGap) / stdGap  [clamped to 0–4]
 *   z ≤ 0 → score = 0 (recently appeared, no boost)
 *   Never seen → z = 2.0 (moderately overdue default)
 *
 * Auxiliary signals (applied as multipliers on baseScore):
 *   S3 (+0–30%) sum-bucket observed short vs expected (last-200 draws)
 *   S4 (+0–15%) digit momentum (last-30 draws)
 *   S5 (+0–7%)  sum-bucket overdue ratio — gentle tie-breaker only
 *   S6 (+0–7%)  pair-digit overdue ratio — pairs/triples only; gentle nudge
 *
 * S5/S6 are intentionally capped at +7% each (combined ≤ +14.5%):
 *   They should NOT be strong enough to push a triple to rank #1 by themselves.
 *   Triples have 1/36 base rate; boosting them aggressively amplifies gambler's fallacy.
 */
function modelA(chron) {
  const N = chron.length
  const start200 = Math.max(0, N - 200)  // window for S3
  const start30 = Math.max(0, N - 30)   // window for S4

  // ── Single O(N) pass accumulates all signal data ───────────────────────
  const lastIdx = {}   // combo → last draw index (for gap tracking)
  const gapLists = {}   // combo → array of historical gaps

  const sumCountW = {}   // S3: sum count in last-200 draws
  const digitCntW = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 }  // S4: digit count in last-30

  const sumLastSeen = {}   // S5: last draw index where this sum appeared
  const sumGapList = {}   // S5: gaps between same-sum draws

  const pairLastSeen = {}   // S6: last draw index where this pair-digit fired
  const pairGapList = {}   // S6: gaps between same-pair-digit draws

  for (let i = 0; i < N; i++) {
    const r = chron[i]
    const k = key(r.n1, r.n2, r.n3)
    const s = r.n1 + r.n2 + r.n3

    // Combo gaps (for z-score)
    if (lastIdx[k] !== undefined) {
      if (!gapLists[k]) gapLists[k] = []
      gapLists[k].push(i - lastIdx[k])
    }
    lastIdx[k] = i

    // S3: count sums in last-200 window
    if (i >= start200) sumCountW[s] = (sumCountW[s] || 0) + 1

    // S4: count digits in last-30 window
    if (i >= start30) { digitCntW[r.n1]++; digitCntW[r.n2]++; digitCntW[r.n3]++ }

    // S5: track gap between draws of the same sum
    if (sumLastSeen[s] !== undefined) {
      if (!sumGapList[s]) sumGapList[s] = []
      sumGapList[s].push(i - sumLastSeen[s])
    }
    sumLastSeen[s] = i

    // S6: track gap between draws containing each pair-digit (≥2 dice equal).
    // Avoid double-counting triples (1-1-1) using arithmetic rather than Set.
    const pv1 = (r.n1 === r.n2 || r.n1 === r.n3) ? r.n1 : -1
    const pv2 = (r.n2 === r.n3 && r.n2 !== pv1) ? r.n2 : -1
    if (pv1 !== -1) {
      if (pairLastSeen[pv1] !== undefined) {
        if (!pairGapList[pv1]) pairGapList[pv1] = []
        pairGapList[pv1].push(i - pairLastSeen[pv1])
      }
      pairLastSeen[pv1] = i
    }
    if (pv2 !== -1) {
      if (pairLastSeen[pv2] !== undefined) {
        if (!pairGapList[pv2]) pairGapList[pv2] = []
        pairGapList[pv2].push(i - pairLastSeen[pv2])
      }
      pairLastSeen[pv2] = i
    }
  }

  // ── Derive per-sum and per-digit signals ──────────────────────────────
  // S3: observed deficit vs theoretical expectation over last-200
  const W200 = N - start200
  const sumDev = {}
  for (let s = 3; s <= 18; s++) {
    const expected = W200 * (SUM_COUNT[s] / 216)
    sumDev[s] = expected > 0 ? Math.max(0, expected - (sumCountW[s] || 0)) / expected : 0
  }

  // S4: digit momentum — excess count vs expected in last-30
  const W30 = N - start30
  const expected30 = W30 * 3 / 6    // each digit expected W30*3/6 appearances
  const digitHot = {}
  for (let d = 1; d <= 6; d++) {
    digitHot[d] = expected30 > 0 ? Math.max(0, digitCntW[d] - expected30) / expected30 : 0
  }

  // S5: for each sum, overdue ratio = draws since last / avg gap (>1 = overdue)
  const sumOD = {}
  for (let s = 3; s <= 18; s++) {
    const since = sumLastSeen[s] !== undefined ? N - 1 - sumLastSeen[s] : N
    const g = sumGapList[s] || []
    const avg = g.length ? g.reduce((a, b) => a + b, 0) / g.length : N
    sumOD[s] = avg > 0 ? since / avg : 1
  }

  // S6: for each pair-digit, overdue ratio
  const pairOD = {}
  for (let v = 1; v <= 6; v++) {
    const since = pairLastSeen[v] !== undefined ? N - 1 - pairLastSeen[v] : N
    const g = pairGapList[v] || []
    const avg = g.length ? g.reduce((a, b) => a + b, 0) / g.length : N
    pairOD[v] = avg > 0 ? since / avg : 1
  }

  // ── Score each of the 216 combos ──────────────────────────────────────
  const scores = {}
  const zMap = {}
  const gapMeta = {}

  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    const gaps = gapLists[k] || []
    const curGap = lastIdx[k] !== undefined ? N - 1 - lastIdx[k] : N

    const avg = gaps.length ? gaps.reduce((s, v) => s + v, 0) / gaps.length : null
    const variance = gaps.length > 1
      ? gaps.reduce((acc, g) => acc + (g - avg) ** 2, 0) / gaps.length
      : null
    const std = variance !== null ? Math.sqrt(variance) : null

    let z
    if (avg !== null && std !== null && std >= 1) {
      z = (curGap - avg) / std
    } else if (avg !== null) {
      z = Math.max(-2, Math.min(2, (curGap - avg) / avg))
    } else {
      z = 2.0  // never seen — treat as moderately overdue
    }

    zMap[k] = z
    gapMeta[k] = {
      currentGap: curGap,
      avgGap: avg,
      stability: avg !== null && std !== null && std > 0 ? avg / std : null,
    }

    const baseScore = Math.max(0, Math.min(4, z))

    // Sample-size decay: shrink modelA influence when data is sparse.
    // log(N)/log(5000) reaches 1.0 at 5000 draws; below that, caps overconfident z-scores.
    const sampleDecay = Math.min(1, Math.log(Math.max(N, 2)) / Math.log(5000))

    // S3 & S4 — can add up to 30% + 15% for strong signals
    const s3 = 1 + sumDev[a + b + c] * 0.30
    const digits = a === b && b === c ? [a] : a === b ? [a, c] : a === c ? [a, b] : b === c ? [b, a] : [a, b, c]
    const avgHot = digits.reduce((acc, d) => acc + digitHot[d], 0) / digits.length
    const s4 = 1 + avgHot * 0.15

    // S5 — gentle sum-overdue nudge: max +7%
    const sumRatio = sumOD[a + b + c] || 1
    const s5 = sumRatio > 1 ? 1 + Math.min(0.07, (sumRatio - 1) * 0.05) : 1

    // S6 — gentle pair-digit-overdue nudge: max +7%, pairs/triples only
    // Triples are rare (1/36 per draw); capping S6 prevents them being
    // inflated to rank #1 purely by pair overdue signal.
    let s6 = 1
    const pat = classify(a, b, c)
    if (pat === 'pair' || pat === 'triple') {
      const pairDigit = (a === b || a === c) ? a : b
      const pRatio = pairOD[pairDigit] || 1
      s6 = pRatio > 1 ? 1 + Math.min(0.07, (pRatio - 1) * 0.04) : 1
    }

    scores[k] = baseScore * sampleDecay * s3 * s4 * s5 * s6
  }
  return { scores, zMap, gapMeta }
}

// ── MODEL B: Markov order-2 ───────────────────────────────────────────────

function buildMarkov2(chron) {
  const map = {}
  for (let i = 2; i < chron.length; i++) {
    const p2 = key(chron[i - 2].n1, chron[i - 2].n2, chron[i - 2].n3)
    const p1 = key(chron[i - 1].n1, chron[i - 1].n2, chron[i - 1].n3)
    const cur = key(chron[i].n1, chron[i].n2, chron[i].n3)
    const sk = `${p2}|${p1}`
    if (!map[sk]) map[sk] = {}
    map[sk][cur] = (map[sk][cur] || 0) + 1
  }
  return map
}

/**
 * Model B: Markov order-2 with Laplace smoothing (α=0.5) and fallback chain:
 *   order-2 (any observations) → order-1 → Laplace-uniform = 1/216
 * Laplace smoothing: P(k|ctx) = (count(k,ctx) + α) / (total(ctx) + α×216)
 * Eliminates zero probabilities and removes ≥5-obs threshold — handles sparse contexts.
 */
function modelB(chron) {
  const N = chron.length
  const uniform = () => {
    const u = {}
    for (const [a, b, c] of ALL_COMBOS) u[key(a, b, c)] = 1 / 216
    return u
  }
  if (N < 1) return uniform()

  const p1k = key(chron[N - 1].n1, chron[N - 1].n2, chron[N - 1].n3)

  // Try order-2
  if (N >= 3) {
    const p2k = key(chron[N - 2].n1, chron[N - 2].n2, chron[N - 2].n3)
    const mk2 = buildMarkov2(chron)
    const trans2 = mk2[`${p2k}|${p1k}`]
    if (trans2) {
      const total2 = Object.values(trans2).reduce((s, v) => s + v, 0)
      const sc = {}
      for (const [a, b, c] of ALL_COMBOS) {
        const k = key(a, b, c)
        sc[k] = ((trans2[k] || 0) + ALPHA) / (total2 + ALPHA * 216)
      }
      return sc
    }
  }

  // Fallback to order-1
  const mk1 = {}
  for (let i = 1; i < N; i++) {
    const prev = key(chron[i - 1].n1, chron[i - 1].n2, chron[i - 1].n3)
    const cur = key(chron[i].n1, chron[i].n2, chron[i].n3)
    if (!mk1[prev]) mk1[prev] = {}
    mk1[prev][cur] = (mk1[prev][cur] || 0) + 1
  }
  const trans1 = mk1[p1k]
  if (trans1) {
    const total1 = Object.values(trans1).reduce((s, v) => s + v, 0)
    const sc = {}
    for (const [a, b, c] of ALL_COMBOS) {
      const k = key(a, b, c)
      sc[k] = ((trans1[k] || 0) + ALPHA) / (total1 + ALPHA * 216)
    }
    return sc
  }

  // Final fallback: Laplace-uniform = 1/216 (equivalent since no context observed)
  return uniform()
}

// ── MODEL C: Time-of-day session frequency ratio ──────────────────────────

function getSession(hoursOrDateStr) {
  const h = typeof hoursOrDateStr === 'number'
    ? hoursOrDateStr
    : new Date(hoursOrDateStr).getHours()
  if (h >= 6 && h < 12) return 'morning'
  if (h >= 12 && h < 18) return 'afternoon'
  return 'evening'
}

/**
 * Model C: frequency ratio for the current day-part session.
 * Returns {} when < 20 draws in session (caller redistributes weight to A+B).
 */
function modelC(chron, now) {
  const cur = getSession(now.getHours())
  const sessData = chron.filter(r => r.drawTime && getSession(r.drawTime) === cur)
  if (sessData.length < 20) return {}

  const W = sessData.length
  const expected = W / 216
  const countMap = {}
  for (const r of sessData) {
    const k = key(r.n1, r.n2, r.n3)
    countMap[k] = (countMap[k] || 0) + 1
  }
  const sc = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    sc[k] = (countMap[k] || 0) / expected
  }
  return sc
}

// ── S2: Triple streak boost (applied AFTER ensemble) ─────────────────────

/**
 * Returns a conservative multiplier for triple combos.
 *
 * Rules:
 *   - no_pattern      → no boost at all
 *   - weak_pattern    → tiny boost only after clear drought
 *   - pattern_detected→ gentle boost, never dominant
 *
 * This keeps triples informational instead of letting them dominate the top-10
 * while the model is still learning on a near-random game.
 */
function tripleBoostMult(chron, verdict = 'weak_pattern') {
  let sinceTriple = 0
  for (let i = chron.length - 1; i >= 0; i--) {
    const pat = chron[i].pattern || classify(chron[i].n1, chron[i].n2, chron[i].n3)
    if (pat === 'triple') break
    sinceTriple++
  }
  const EXPECTED_GAP = 36     // 1-in-36 draws is a triple
  const ratio = sinceTriple / EXPECTED_GAP
  if (verdict === 'no_pattern') return 1.0
  if (ratio <= 1.15) return 1.0

  if (verdict === 'pattern_detected') {
    return Math.min(1.12, 1 + (ratio - 1.15) * 0.08)
  }

  return Math.min(1.06, 1 + (ratio - 1.15) * 0.04)
}

// ── ENSEMBLE ──────────────────────────────────────────────────────────────

function ensembleAll(chron, now) {
  // Reality-aware weight shrinking: when statistical tests find no detectable pattern,
  // shrink pattern-detection model weights (A, B, D) toward zero so the ensemble
  // produces more uniform predictions — intellectually honest for a near-random game.
  const statRes = runStatTests(chron)
  const SHRINK_MAP = { no_pattern: 0.5, weak_pattern: 0.75, pattern_detected: 1.0 }
  const shrink = SHRINK_MAP[statRes.verdict] ?? 0.75

  const { scores: rawA, zMap, gapMeta } = modelA(chron)  // gapMeta built in same O(N) pass
  const rawB = modelB(chron)
  const rawC = modelC(chron, now)

  // Auto-disable Model D (k-NN) when learned weights penalize it (wD < 0)
  // — avoids spending compute on a model that currently adds noise.
  const lw = _learnedWeights
  const killD = lw !== null && (lw.wD ?? 0) < 0
  const rawD = killD ? {} : modelD(chron)

  // Model E: Python GBM prior (loaded from python/ml_output.json, if present & fresh)
  const rawE = getGBMScores(chron.length)

  const A = rankNorm(rawA)
  const B = rankNorm(rawB)
  const hasC = Object.keys(rawC).length > 0
  const hasD = Object.keys(rawD).length > 0
  const hasE = Object.keys(rawE).length > 0
  const C = hasC ? rankNorm(rawC) : {}
  const D = hasD ? rankNorm(rawD) : {}
  const E = hasE ? rankNorm(rawE) : {}

  // Fixed fallback weights (graceful degradation when models inactive)
  const wA_fixed = hasC && hasD ? 0.40 : hasD ? 0.45 : hasC ? 0.50 : 0.60
  const wB_fixed = hasC && hasD ? 0.25 : hasD ? 0.35 : hasC ? 0.30 : 0.40
  const wC_fixed = hasC ? (hasD ? 0.15 : 0.20) : 0
  const wD_fixed = hasD ? 0.20 : 0
  // E not used in fixed fallback — requires trained weight to avoid guessing

  const tripleBoost = tripleBoostMult(chron, statRes.verdict)

  const results = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    const pat = classify(a, b, c)
    const sA = A[k] ?? 0.5
    const sB = B[k] ?? 0.5
    const sC = hasC ? (C[k] ?? 0.5) : 0
    // k-NN: combos absent from similar historical contexts score 0 (strong signal)
    // sD=0 when killD=true (wD<0 → k-NN currently harmful, auto-disabled)
    const sD = hasD ? (D[k] ?? 0) : 0
    // GBM prior: fixed distribution over combos from Python offline training
    const sE = hasE ? (E[k] ?? 0.5) : 0

    // Sigmoid ensemble (learned) vs fixed linear (fallback)
    // NOTE: sC=0/sD=0/sE=0 when inactive → learned weights auto-degrade.
    //       Sigmoid is monotone → same ranking as linear; benefit is learned
    //       weights that can be negative (penalise noisy models).
    let score
    if (lw) {
      const wE = lw.wE ?? 0
      // Apply shrinkFactor to pattern-detecting models (A, B, D); leave session (C) and GBM (E) unchanged
      score = sigmoid((lw.wA * shrink) * sA + (lw.wB * shrink) * sB + lw.wC * sC + (lw.wD * shrink) * sD + wE * sE + lw.bias)
    } else {
      score = wA_fixed * sA + wB_fixed * sB + wC_fixed * sC + wD_fixed * sD
    }

    // Apply triple streak boost AFTER ensemble combination
    if (pat === 'triple') score *= tripleBoost

    results[k] = {
      combo: k,
      pat,
      sum: a + b + c,
      score,
      z: zMap[k],
      currentGap: gapMeta[k].currentGap,
      avgGap: gapMeta[k].avgGap,
      stability: gapMeta[k].stability,
      statNorm: +sA.toFixed(4),
      mk2Norm: +sB.toFixed(4),
      sessNorm: +(hasC ? (C[k] ?? 0) : 0).toFixed(4),
      mlNorm: +(hasD ? (D[k] ?? 0) : 0).toFixed(4),
      gbmNorm: +(hasE ? (E[k] ?? 0) : 0).toFixed(4),
    }
  }

  // Compute score range across all 216 combos for confidence normalization
  const allScores = Object.values(results).map(r => r.score)
  const scoreMin = Math.min(...allScores)
  const scoreMax = Math.max(...allScores)
  for (const r of Object.values(results)) {
    r.scoreRankPct = scoreMax > scoreMin
      ? +((r.score - scoreMin) / (scoreMax - scoreMin) * 100).toFixed(1)
      : 50
  }

  return results
}

// ── Diversity cap + top-10 selection ─────────────────────────────────────

function selectTop10(results) {
  const sorted = Object.values(results).sort((a, b) => b.score - a.score)
  const capPat = { triple: 2, pair: 4, normal: 4 }
  const countPat = { triple: 0, pair: 0, normal: 0 }
  const digitCnt = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 }
  const top10 = []
  const chosen = new Set()

  // Pure score-based ranking — no forced overrides.
  // Triples get boost via tripleBoostMult() applied earlier in ensembleAll();
  // if they score high enough they rise naturally. Forcing them in by z-score
  // produced artificial top-1 placements that reduced overall accuracy.

  // Pass 1: full diversity constraints
  for (const r of sorted) {
    if (top10.length >= 10) break
    if (chosen.has(r.combo)) continue
    if (countPat[r.pat] >= capPat[r.pat]) continue
    const digits = [...new Set(r.combo.split('-').map(Number))]
    if (digits.some(d => digitCnt[d] >= 2)) continue
    top10.push(r); chosen.add(r.combo); countPat[r.pat]++
    digits.forEach(d => digitCnt[d]++)
  }

  // Pass 2: relax digit-sharing, keep pattern cap
  for (const r of sorted) {
    if (top10.length >= 10) break
    if (!chosen.has(r.combo) && countPat[r.pat] < capPat[r.pat]) {
      top10.push(r); chosen.add(r.combo); countPat[r.pat]++
    }
  }

  // Pass 3: no constraints
  for (const r of sorted) {
    if (top10.length >= 10) break
    if (!chosen.has(r.combo)) { top10.push(r); chosen.add(r.combo) }
  }

  return top10.sort((a, b) => b.score - a.score)
}

// ── Public API ────────────────────────────────────────────────────────────

function predictRanked(data) {
  if (!data) data = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'))
  if (!data || data.length < 2) return { top10: [], tripleSignal: null }
  const chron = [...data].sort((a, b) => Number(a.ky) - Number(b.ky))
  const now = new Date()
  const statRes = runStatTests(chron)
  const all = ensembleAll(chron, now)
  const top10 = selectTop10(all)

  // ── Triple signal: single O(N) pass for all triple stats ────────────
  const EXPECTED_GAP = 36 // 6/216 — one triple every 36 draws on average
  let tripleCount = 0
  let lastTripleIdx = -1
  const tripleGaps = []
  chron.forEach((r, i) => {
    const pat = r.pattern || classify(r.n1, r.n2, r.n3)
    if (pat === 'triple') {
      tripleCount++
      if (lastTripleIdx >= 0) tripleGaps.push(i - lastTripleIdx)
      lastTripleIdx = i
    }
  })
  const sinceTriple = lastTripleIdx >= 0 ? chron.length - 1 - lastTripleIdx : chron.length
  const overdueRatio = sinceTriple / EXPECTED_GAP
  const avgTripleGap = tripleGaps.length
    ? +(tripleGaps.reduce((a, b) => a + b, 0) / tripleGaps.length).toFixed(1)
    : EXPECTED_GAP

  const boostMult = tripleBoostMult(chron, statRes.verdict)

  // Only show triples that both survived top10 selection and are strong enough
  // on the final score scale. Otherwise the card stays informational only.
  const hotTriples = top10
    .filter(r => r.pat === 'triple' && (r.scoreRankPct ?? 0) >= 70)
    .map(r => r.combo)

  const tripleSignal = {
    sinceLastTriple: sinceTriple,
    expectedGap: EXPECTED_GAP,
    avgGap: avgTripleGap,
    overdueRatio: +overdueRatio.toFixed(2),
    boostMult: +boostMult.toFixed(2),
    appeared: tripleCount,
    verdict: statRes.verdict,
    aiConfirmed: hotTriples.length > 0,
    hotTriples,
  }

  const mapped = top10.map(r => ({
    combo: r.combo,
    score: +r.score.toFixed(4),
    scoreRankPct: r.scoreRankPct ?? 50,
    pct: 0,           // filled by server.js
    overdueRatio: r.z,
    comboGap: r.currentGap,
    sumOD: 0,
    pat: r.pat,
    stability: r.stability,
    zScore: r.z,
    statNorm: r.statNorm,
    mk2Norm: r.mk2Norm,
    sessNorm: r.sessNorm,
    mlNorm: r.mlNorm ?? 0,
    gbmNorm: r.gbmNorm ?? 0,
    coreNorm: r.statNorm,
    chiNorm: 0,
  }))

  return { top10: mapped, tripleSignal }
}

/** Score map for all 216 combos — used by /stats backtest. */
function predict(data) {
  if (!data) data = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'))
  if (!data || data.length < 2) return {}
  const chron = [...data].sort((a, b) => Number(a.ky) - Number(b.ky))
  const now = new Date()
  const all = ensembleAll(chron, now)
  const out = {}
  for (const [k, v] of Object.entries(all)) out[k] = v.score
  return out
}

/**
 * Returns per-model normalised scores for all 216 combos.
 * Used by scripts/train_weights.js for walk-forward weight optimisation.
 */
function getModelScores(data, now) {
  if (!data || data.length < 2) return {}
  const chron = [...data].sort((a, b) => Number(a.ky) - Number(b.ky))
  if (!now) now = new Date()

  const { scores: rawA } = modelA(chron)
  const rawB = modelB(chron)
  const rawC = modelC(chron, now)
  // Mirror the auto-disable logic from ensembleAll
  const lw_gs = _learnedWeights
  const killD_gs = lw_gs !== null && (lw_gs.wD ?? 0) < 0
  const rawD = killD_gs ? {} : modelD(chron)

  const rawE = getGBMScores(chron.length)

  const A = rankNorm(rawA)
  const B = rankNorm(rawB)
  const hasC = Object.keys(rawC).length > 0
  const hasD = Object.keys(rawD).length > 0
  const hasE = Object.keys(rawE).length > 0
  const C = hasC ? rankNorm(rawC) : {}
  const D = hasD ? rankNorm(rawD) : {}
  const E = hasE ? rankNorm(rawE) : {}

  const result = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    result[k] = {
      sA: A[k] ?? 0.5,
      sB: B[k] ?? 0.5,
      sC: hasC ? (C[k] ?? 0.5) : 0,
      sD: hasD ? (D[k] ?? 0) : 0,
      sE: hasE ? (E[k] ?? 0.5) : 0,
    }
  }
  return result
}

predict.ranked = predictRanked
predict.getModelScores = getModelScores
predict.reloadWeights = loadLearnedWeights
predict.reloadGBM = loadGBMScores
module.exports = predict
