'use strict'
/**
 * predictor/ensemble.js — v4
 *
 * 3-model ensemble — normalize each to [0,1] then combine equally:
 *
 *   MODEL A — Statistical z-score (overdueness measure)     [40%]
 *     z = (currentGap – avgGap) / stdGap; clamped score = max(0, min(4, z))
 *     Overdue (z > 0) → boosted; recently appeared (z ≤ 0) → score=0
 *     Augmented by S3 (sum deviation) + S4 (digit momentum)
 *     Raw z exported as `zScore`; bypass cap when z > 2.5
 *
 *   MODEL B — Markov order-2 (transition probability)           [25%]
 *     P(next | prev-2, prev-1); fallback to order-1; then 1/216
 *     Fallback chain: never crashes on undefined key
 *
 *   MODEL C — Time-of-day session model (frequency ratio)       [15%]
 *     morning 6–12h / afternoon 12–18h / evening 18–6h
 *     When < 20 draws in current session → weight=0 → redistrib to A+B+D
 *
 *   MODEL D — k-NN Temporal Similarity (pure-JS ML)            [20%]
 *     Finds k most historically similar draw contexts (Euclidean on lag
 *     features), scores combos by inverse-distance-weighted hit count.
 *     Disabled when history < K_MIN+WINDOW+1 draws (first ~25 draws).
 *
 * Triple boost (S2) applied AFTER ensemble — not inside any model:
 *   sinceTriple = draws since last triple appeared
 *   mult = min(3.0, 1 + (1 – (210/216)^sinceTriple) * 2)
 *
 * Diversity cap bypass:
 *   Combos with z > 2.5 (severely overdue) → forced into top-10
 *   sorted by z DESC (most overdue first) — max 3 bypass slots
 *
 * Confidence display cap: 75% — enforced in server.js on the pct field
 */

const path = require('path')
const fs = require('fs')
const modelD = require('./model_d')

const HISTORY_FILE = path.join(__dirname, '../dataset/history.json')
const WEIGHTS_FILE = path.join(__dirname, '../dataset/model.json')
const GBM_FILE    = path.join(__dirname, '../python/ml_output.json')
const GBM_MAX_STALENESS = 200  // records; invalidate GBM scores if dataset grew > this

// ── Learned weights (sigmoid ensemble) ────────────────────────────────────
// Trained by: node scripts/train_weights.js
// Falls back to fixed weights if file not found or parse error.

function sigmoid(x) { return 1 / (1 + Math.exp(-x)) }

let _learnedWeights = null
function loadLearnedWeights() {
  try {
    const raw = fs.readFileSync(WEIGHTS_FILE, 'utf8')
    const w = JSON.parse(raw)
    // Minimal validation — must have numeric weights
    if (typeof w.wA === 'number' && typeof w.wB === 'number') {
      // Only activate if training confirmed validation improvement (or flag absent = legacy)
      if (w.improvesValid === false) {
        _learnedWeights = null    // training found no improvement; keep fixed weights
      } else {
        _learnedWeights = w
      }
    } else {
      _learnedWeights = null
    }
  } catch (_) {
    _learnedWeights = null
  }
}
loadLearnedWeights()  // load once at startup

// ── Model E: Python GBM scores (offline, optional) ────────────────────────
// Generated by: python python/ml_predictor.py  → python/ml_output.json
// Treated as a fixed prior distribution over combos. When stale (dataset grew
// > GBM_MAX_STALENESS records since GBM run), scores are ignored (sE = 0).

let _gbmScores = null
let _gbmTrainRecords = 0

function loadGBMScores() {
  try {
    const raw = fs.readFileSync(GBM_FILE, 'utf8')
    const obj = JSON.parse(raw)
    if (obj.scores && typeof obj.scores === 'object') {
      _gbmScores = obj.scores
      _gbmTrainRecords = obj.trainRecords || 0
    } else {
      _gbmScores = null
    }
  } catch (_) {
    _gbmScores = null
  }
}
loadGBMScores()

/** Returns GBM score map or {} when file absent / stale. */
function getGBMScores(currentN) {
  if (!_gbmScores) return {}
  if (Math.abs(currentN - _gbmTrainRecords) > GBM_MAX_STALENESS) return {}
  return _gbmScores
}
const SUM_COUNT = {
  3: 1, 4: 3, 5: 6, 6: 10, 7: 15, 8: 21,
  9: 25, 10: 27, 11: 27, 12: 25, 13: 21, 14: 15,
  15: 10, 16: 6, 17: 3, 18: 1,
}

function key(n1, n2, n3) { return `${n1}-${n2}-${n3}` }

function classify(a, b, c) {
  if (a === b && b === c) return 'triple'
  if (a === b || b === c || a === c) return 'pair'
  return 'normal'
}

const ALL_COMBOS = []
for (let a = 1; a <= 6; a++)
  for (let b = 1; b <= 6; b++)
    for (let c = 1; c <= 6; c++)
      ALL_COMBOS.push([a, b, c])

/**
 * Min-max normalize a score map {key: number} → {key: [0,1]}.
 * All-equal values → 0.5 (signal is uniform / uninformative).
 */
function minMaxNorm(scoreMap) {
  const keys = Object.keys(scoreMap)
  if (!keys.length) return scoreMap
  const vals = keys.map(k => scoreMap[k]).filter(v => isFinite(v))
  const min = Math.min(...vals)
  const max = Math.max(...vals)
  const range = max - min
  const out = {}
  for (const k of keys) {
    out[k] = range > 0 ? (scoreMap[k] - min) / range : 0.5
  }
  return out
}

// ── MODEL A: Statistical z-score ──────────────────────────────────────────

function sig3SumDeviation(chron) {
  const window = chron.slice(-200)
  const W = window.length
  const countMap = {}
  for (const r of window) countMap[r.sum] = (countMap[r.sum] || 0) + 1
  const dev = {}
  for (let s = 3; s <= 18; s++) {
    const expected = W * (SUM_COUNT[s] / 216)
    const actual = countMap[s] || 0
    dev[s] = expected > 0 ? Math.max(0, expected - actual) / expected : 0
  }
  return dev
}

function sig4DigitMomentum(chron) {
  const window = chron.slice(-30)
  const W = window.length
  const expected = W * 3 / 6
  const count = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 }
  for (const r of window) { count[r.n1]++; count[r.n2]++; count[r.n3]++ }
  const hot = {}
  for (let d = 1; d <= 6; d++) {
    hot[d] = expected > 0 ? Math.max(0, count[d] - expected) / expected : 0
  }
  return hot
}

/**
 * Model A: gap-based z-score — how many std deviations overdue is each combo?
 *
 *   z = (currentGap – avgGap) / stdGap
 *
 *   z > 0  → overdue (waited longer than average) → gets score boost
 *   z ≤ 0  → recently appeared → score = 0 (floor, no negative penalty)
 *   z is clamped to [0, 4] to prevent outlier combos with tiny stdGap from
 *   dominating (e.g., a combo with stdGap=3 and curGap=500 → z=126 → capped to 4)
 *
 * Special cases:
 *   - Only 1 historical gap (no stdGap): use ratio (curGap – avgGap) / avgGap, cap ±2
 *   - Never seen: z = 2.0  (moderately overdue default)
 *
 * Augmented by S3 (sum deviation) and S4 (digit momentum) as tie-breakers.
 */
function modelA(chron) {
  const N = chron.length

  // Build gap history for every combo
  const lastIdx = {}
  const gapLists = {}
  chron.forEach((r, i) => {
    const k = key(r.n1, r.n2, r.n3)
    if (lastIdx[k] !== undefined) {
      if (!gapLists[k]) gapLists[k] = []
      gapLists[k].push(i - lastIdx[k])
    }
    lastIdx[k] = i
  })

  const sumDev = sig3SumDeviation(chron)
  const digitHot = sig4DigitMomentum(chron)

  const scores = {}
  const zMap = {}

  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    const gaps = gapLists[k] || []
    const curGap = lastIdx[k] !== undefined ? N - 1 - lastIdx[k] : N

    const avg = gaps.length ? gaps.reduce((s, v) => s + v, 0) / gaps.length : null
    const variance = gaps.length > 1
      ? gaps.reduce((acc, g) => acc + (g - avg) ** 2, 0) / gaps.length
      : null
    const std = variance !== null ? Math.sqrt(variance) : null

    let z
    if (avg !== null && std !== null && std >= 1) {
      // ≥2 historical gaps: full gap z-score
      z = (curGap - avg) / std
    } else if (avg !== null) {
      // exactly 1 historical gap: ratio-based, capped to [-2, 2]
      z = Math.max(-2, Math.min(2, (curGap - avg) / avg))
    } else {
      // never seen before
      z = 2.0
    }

    zMap[k] = z

    // Score: clamp to [0, 4] — only overdue combos get a boost
    const baseScore = Math.max(0, Math.min(4, z))

    const s3 = 1 + sumDev[a + b + c] * 0.30
    const digits = [...new Set([a, b, c])]
    const avgHot = digits.reduce((acc, d) => acc + digitHot[d], 0) / digits.length
    const s4 = 1 + avgHot * 0.15

    scores[k] = baseScore * s3 * s4
  }
  return { scores, zMap }
}

// ── MODEL B: Markov order-2 ───────────────────────────────────────────────

function buildMarkov2(chron) {
  const map = {}
  for (let i = 2; i < chron.length; i++) {
    const p2 = key(chron[i - 2].n1, chron[i - 2].n2, chron[i - 2].n3)
    const p1 = key(chron[i - 1].n1, chron[i - 1].n2, chron[i - 1].n3)
    const cur = key(chron[i].n1, chron[i].n2, chron[i].n3)
    const sk = `${p2}|${p1}`
    if (!map[sk]) map[sk] = {}
    map[sk][cur] = (map[sk][cur] || 0) + 1
  }
  return map
}

/**
 * Model B: Markov order-2 with fallback chain:
 *   order-2 (≥5 observations) → order-1 → uniform 1/216
 */
function modelB(chron) {
  const N = chron.length
  const uniform = () => {
    const u = {}
    for (const [a, b, c] of ALL_COMBOS) u[key(a, b, c)] = 1 / 216
    return u
  }
  if (N < 1) return uniform()

  const p1k = key(chron[N - 1].n1, chron[N - 1].n2, chron[N - 1].n3)

  // Try order-2
  if (N >= 3) {
    const p2k = key(chron[N - 2].n1, chron[N - 2].n2, chron[N - 2].n3)
    const mk2 = buildMarkov2(chron)
    const trans2 = mk2[`${p2k}|${p1k}`]
    if (trans2) {
      const total2 = Object.values(trans2).reduce((s, v) => s + v, 0)
      if (total2 >= 5) {
        const sc = {}
        for (const [a, b, c] of ALL_COMBOS) {
          const k = key(a, b, c)
          sc[k] = (trans2[k] || 0) / total2
        }
        return sc
      }
    }
  }

  // Fallback to order-1
  const mk1 = {}
  for (let i = 1; i < N; i++) {
    const prev = key(chron[i - 1].n1, chron[i - 1].n2, chron[i - 1].n3)
    const cur = key(chron[i].n1, chron[i].n2, chron[i].n3)
    if (!mk1[prev]) mk1[prev] = {}
    mk1[prev][cur] = (mk1[prev][cur] || 0) + 1
  }
  const trans1 = mk1[p1k]
  if (trans1) {
    const total1 = Object.values(trans1).reduce((s, v) => s + v, 0)
    if (total1 > 0) {
      const sc = {}
      for (const [a, b, c] of ALL_COMBOS) {
        const k = key(a, b, c)
        sc[k] = (trans1[k] || 0) / total1
      }
      return sc
    }
  }

  // Final fallback: uniform
  return uniform()
}

// ── MODEL C: Time-of-day session frequency ratio ──────────────────────────

function getSession(hoursOrDateStr) {
  const h = typeof hoursOrDateStr === 'number'
    ? hoursOrDateStr
    : new Date(hoursOrDateStr).getHours()
  if (h >= 6 && h < 12) return 'morning'
  if (h >= 12 && h < 18) return 'afternoon'
  return 'evening'
}

/**
 * Model C: frequency ratio for the current day-part session.
 * Returns {} when < 20 draws in session (caller redistributes weight to A+B).
 */
function modelC(chron, now) {
  const cur = getSession(now.getHours())
  const sessData = chron.filter(r => r.drawTime && getSession(r.drawTime) === cur)
  if (sessData.length < 20) return {}

  const W = sessData.length
  const expected = W / 216
  const countMap = {}
  for (const r of sessData) {
    const k = key(r.n1, r.n2, r.n3)
    countMap[k] = (countMap[k] || 0) + 1
  }
  const sc = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    sc[k] = (countMap[k] || 0) / expected
  }
  return sc
}

// ── S2: Triple streak boost (applied AFTER ensemble) ─────────────────────

/**
 * Returns a multiplier for triple combos — but ONLY when the drought is
 * longer than the expected average gap (36 draws = 1/36 chance per draw).
 *
 *   ratio = sinceTriple / 36
 *   ratio ≤ 1.0 → no boost (drought is ordinary)
 *   ratio = 1.5 → boost ≈ 1.25×
 *   ratio ≥ 2.0 → max boost 1.5×
 *
 * Previous formula (210/216)^N fired immediately (1.65× after just 14 draws),
 * causing 2 triples to dominate top positions even during a normal no-triple run.
 */
function tripleBoostMult(chron) {
  let sinceTriple = 0
  for (let i = chron.length - 1; i >= 0; i--) {
    const pat = chron[i].pattern || classify(chron[i].n1, chron[i].n2, chron[i].n3)
    if (pat === 'triple') break
    sinceTriple++
  }
  const EXPECTED_GAP = 36     // 1-in-36 draws is a triple
  const ratio = sinceTriple / EXPECTED_GAP
  if (ratio <= 1) return 1.0  // within normal range → no boost
  return Math.min(1.5, 1 + (ratio - 1) * 0.5)
}

// ── Gap / stability metadata (display only, not for scoring) ─────────────

function buildGapMeta(chron) {
  const N = chron.length
  const lastIdx = {}
  const gapLists = {}
  chron.forEach((r, i) => {
    const k = key(r.n1, r.n2, r.n3)
    if (lastIdx[k] !== undefined) {
      if (!gapLists[k]) gapLists[k] = []
      gapLists[k].push(i - lastIdx[k])
    }
    lastIdx[k] = i
  })
  const meta = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    const gaps = gapLists[k] || []
    const avg = gaps.length ? gaps.reduce((s, v) => s + v, 0) / gaps.length : null
    const variance = gaps.length > 1 && avg !== null
      ? gaps.reduce((acc, g) => acc + (g - avg) ** 2, 0) / gaps.length
      : null
    const std = variance !== null ? Math.sqrt(variance) : null
    meta[k] = {
      currentGap: lastIdx[k] !== undefined ? N - 1 - lastIdx[k] : N,
      avgGap: avg,
      stability: avg !== null && std !== null && std > 0 ? avg / std : null,
    }
  }
  return meta
}

// ── ENSEMBLE ──────────────────────────────────────────────────────────────

function ensembleAll(chron, now) {
  const { scores: rawA, zMap } = modelA(chron)
  const rawB = modelB(chron)
  const rawC = modelC(chron, now)

  // Auto-disable Model D (k-NN) when learned weights penalize it (wD < 0)
  // — avoids spending compute on a model that currently adds noise.
  const lw = _learnedWeights
  const killD = lw !== null && (lw.wD ?? 0) < 0
  const rawD = killD ? {} : modelD(chron)

  // Model E: Python GBM prior (loaded from python/ml_output.json, if present & fresh)
  const rawE = getGBMScores(chron.length)

  const gapMeta = buildGapMeta(chron)

  const A = minMaxNorm(rawA)
  const B = minMaxNorm(rawB)
  const hasC = Object.keys(rawC).length > 0
  const hasD = Object.keys(rawD).length > 0
  const hasE = Object.keys(rawE).length > 0
  const C = hasC ? minMaxNorm(rawC) : {}
  const D = hasD ? minMaxNorm(rawD) : {}
  const E = hasE ? minMaxNorm(rawE) : {}

  // Fixed fallback weights (graceful degradation when models inactive)
  const wA_fixed = hasC && hasD ? 0.40 : hasD ? 0.45 : hasC ? 0.50 : 0.60
  const wB_fixed = hasC && hasD ? 0.25 : hasD ? 0.35 : hasC ? 0.30 : 0.40
  const wC_fixed = hasC ? (hasD ? 0.15 : 0.20) : 0
  const wD_fixed = hasD ? 0.20 : 0
  // E not used in fixed fallback — requires trained weight to avoid guessing

  const tripleBoost = tripleBoostMult(chron)

  const results = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    const pat = classify(a, b, c)
    const sA = A[k] ?? 0.5
    const sB = B[k] ?? 0.5
    const sC = hasC ? (C[k] ?? 0.5) : 0
    // k-NN: combos absent from similar historical contexts score 0 (strong signal)
    // sD=0 when killD=true (wD<0 → k-NN currently harmful, auto-disabled)
    const sD = hasD ? (D[k] ?? 0) : 0
    // GBM prior: fixed distribution over combos from Python offline training
    const sE = hasE ? (E[k] ?? 0.5) : 0

    // Sigmoid ensemble (learned) vs fixed linear (fallback)
    // NOTE: sC=0/sD=0/sE=0 when inactive → learned weights auto-degrade.
    //       Sigmoid is monotone → same ranking as linear; benefit is learned
    //       weights that can be negative (penalise noisy models).
    let score
    if (lw) {
      const wE = lw.wE ?? 0
      score = sigmoid(lw.wA * sA + lw.wB * sB + lw.wC * sC + lw.wD * sD + wE * sE + lw.bias)
    } else {
      score = wA_fixed * sA + wB_fixed * sB + wC_fixed * sC + wD_fixed * sD
    }

    // Apply triple streak boost AFTER ensemble combination
    if (pat === 'triple') score *= tripleBoost

    results[k] = {
      combo: k,
      pat,
      sum: a + b + c,
      score,
      z: zMap[k],
      currentGap: gapMeta[k].currentGap,
      avgGap: gapMeta[k].avgGap,
      stability: gapMeta[k].stability,
      statNorm: +sA.toFixed(4),
      mk2Norm: +sB.toFixed(4),
      sessNorm: +(hasC ? (C[k] ?? 0) : 0).toFixed(4),
      mlNorm:  +(hasD ? (D[k] ?? 0) : 0).toFixed(4),
      gbmNorm: +(hasE ? (E[k] ?? 0) : 0).toFixed(4),
    }
  }
  return results
}

// ── Diversity cap + top-10 selection ─────────────────────────────────────

function selectTop10(results) {
  const sorted = Object.values(results).sort((a, b) => b.score - a.score)
  const capPat = { triple: 2, pair: 4, normal: 4 }
  const countPat = { triple: 0, pair: 0, normal: 0 }
  const digitCnt = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 }
  const top10 = []
  const chosen = new Set()

  // Pass 0: bypass — force top-3 MOST OVERDUE combos (z > 2.5) into top-10
  // Sort by z-score DESC so the truly most-overdue always get the slots,
  // not just the highest-scoring ones (which Markov might dominate).
  // Require at least comboGap data to trust the z-score (min 3 gaps = 4 appearances).
  const overdueByZ = sorted
    .filter(r => r.z !== null && r.z > 2.5 && r.currentGap != null)
    .sort((a, b) => b.z - a.z)
  for (const r of overdueByZ) {
    if (top10.length >= 3) break
    top10.push(r); chosen.add(r.combo); countPat[r.pat]++
    const digits = [...new Set(r.combo.split('-').map(Number))]
    digits.forEach(d => digitCnt[d]++)
  }

  // Pass 1: full diversity constraints
  for (const r of sorted) {
    if (top10.length >= 10) break
    if (chosen.has(r.combo)) continue
    if (countPat[r.pat] >= capPat[r.pat]) continue
    const digits = [...new Set(r.combo.split('-').map(Number))]
    if (digits.some(d => digitCnt[d] >= 2)) continue
    top10.push(r); chosen.add(r.combo); countPat[r.pat]++
    digits.forEach(d => digitCnt[d]++)
  }

  // Pass 2: relax digit-sharing, keep pattern cap
  for (const r of sorted) {
    if (top10.length >= 10) break
    if (!chosen.has(r.combo) && countPat[r.pat] < capPat[r.pat]) {
      top10.push(r); chosen.add(r.combo); countPat[r.pat]++
    }
  }

  // Pass 3: no constraints
  for (const r of sorted) {
    if (top10.length >= 10) break
    if (!chosen.has(r.combo)) { top10.push(r); chosen.add(r.combo) }
  }

  return top10.sort((a, b) => b.score - a.score)
}

// ── Public API ────────────────────────────────────────────────────────────

function predictRanked(data) {
  if (!data) data = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'))
  if (!data || data.length < 2) return []
  const chron = [...data].sort((a, b) => Number(a.ky) - Number(b.ky))
  const now = new Date()
  const all = ensembleAll(chron, now)
  const top10 = selectTop10(all)
  return top10.map(r => ({
    combo: r.combo,
    score: +r.score.toFixed(4),
    pct: 0,           // filled by server.js, capped at 75%
    overdueRatio: r.z,        // gap-based z (positive = overdue)
    comboGap: r.currentGap,
    sumOD: 0,           // kept for API compat
    pat: r.pat,
    stability: r.stability,
    // 4-model breakdown
    zScore: r.z,
    statNorm: r.statNorm,
    mk2Norm: r.mk2Norm,
    sessNorm: r.sessNorm,
    mlNorm: r.mlNorm ?? 0,
    // legacy compat — some older UI code may reference these
    coreNorm: r.statNorm,
    chiNorm: 0,
  }))
}

/** Score map for all 216 combos — used by /stats backtest. */
function predict(data) {
  if (!data) data = JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'))
  if (!data || data.length < 2) return {}
  const chron = [...data].sort((a, b) => Number(a.ky) - Number(b.ky))
  const now = new Date()
  const all = ensembleAll(chron, now)
  const out = {}
  for (const [k, v] of Object.entries(all)) out[k] = v.score
  return out
}

/**
 * Returns per-model normalised scores for all 216 combos.
 * Used by scripts/train_weights.js for walk-forward weight optimisation.
 */
function getModelScores(data, now) {
  if (!data || data.length < 2) return {}
  const chron = [...data].sort((a, b) => Number(a.ky) - Number(b.ky))
  if (!now) now = new Date()

  const { scores: rawA } = modelA(chron)
  const rawB = modelB(chron)
  const rawC = modelC(chron, now)
  // Mirror the auto-disable logic from ensembleAll
  const lw_gs = _learnedWeights
  const killD_gs = lw_gs !== null && (lw_gs.wD ?? 0) < 0
  const rawD = killD_gs ? {} : modelD(chron)

  const rawE = getGBMScores(chron.length)

  const A = minMaxNorm(rawA)
  const B = minMaxNorm(rawB)
  const hasC = Object.keys(rawC).length > 0
  const hasD = Object.keys(rawD).length > 0
  const hasE = Object.keys(rawE).length > 0
  const C = hasC ? minMaxNorm(rawC) : {}
  const D = hasD ? minMaxNorm(rawD) : {}
  const E = hasE ? minMaxNorm(rawE) : {}

  const result = {}
  for (const [a, b, c] of ALL_COMBOS) {
    const k = key(a, b, c)
    result[k] = {
      sA: A[k] ?? 0.5,
      sB: B[k] ?? 0.5,
      sC: hasC ? (C[k] ?? 0.5) : 0,
      sD: hasD ? (D[k] ?? 0) : 0,
      sE: hasE ? (E[k] ?? 0.5) : 0,
    }
  }
  return result
}

predict.ranked = predictRanked
predict.getModelScores = getModelScores
predict.reloadWeights = loadLearnedWeights
predict.reloadGBM = loadGBMScores
module.exports = predict
